//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.Security.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAction
    {
        public tblAction()
        {
            this.tblUserActionMappings = new HashSet<tblUserActionMapping>();
        }
    
        public decimal id { get; set; }
        public string name { get; set; }
        public string url { get; set; }
        public string display_name { get; set; }
        public decimal controller_id { get; set; }
        public Nullable<decimal> ui_module_id { get; set; }
        public decimal is_view { get; set; }
        public Nullable<decimal> is_in_menu { get; set; }
        public string class_name { get; set; }
    
        public virtual tblController tblController { get; set; }
        public virtual tblUIModule tblUIModule { get; set; }
        public virtual ICollection<tblUserActionMapping> tblUserActionMappings { get; set; }
    }
}
