//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.Security.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBrokerInformation
    {
        public tblBrokerInformation()
        {
            this.tblBrokerModuleMappings = new HashSet<tblBrokerModuleMapping>();
            this.tblBrokerUsers = new HashSet<tblBrokerUser>();
            this.tblUIModules = new HashSet<tblUIModule>();
        }
    
        public decimal membership_id { get; set; }
        public string Name { get; set; }
        public string short_name { get; set; }
        public string trec_number { get; set; }
        public string mail_address { get; set; }
        public string registration_no { get; set; }
        public Nullable<decimal> paid_up_capital { get; set; }
        public Nullable<decimal> authorized_capital { get; set; }
        public Nullable<decimal> compliance_authority { get; set; }
        public Nullable<int> no_of_ar { get; set; }
        public string contact_no { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> registration_date { get; set; }
        public int active_status_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public Nullable<bool> is_dirty { get; set; }
    
        public virtual ICollection<tblBrokerModuleMapping> tblBrokerModuleMappings { get; set; }
        public virtual ICollection<tblBrokerUser> tblBrokerUsers { get; set; }
        public virtual ICollection<tblUIModule> tblUIModules { get; set; }
    }
}
