//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.Security.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBrokerUserModule
    {
        public tblBrokerUserModule()
        {
            this.tblViews = new HashSet<tblView>();
        }
    
        public string UserId { get; set; }
        public decimal membership_id { get; set; }
        public decimal module_id { get; set; }
    
        public virtual tblBrokerUser tblBrokerUser { get; set; }
        public virtual ICollection<tblView> tblViews { get; set; }
    }
}
