//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.Security.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblController
    {
        public tblController()
        {
            this.tblActions = new HashSet<tblAction>();
        }
    
        public decimal id { get; set; }
        public string name { get; set; }
        public decimal ui_module_id { get; set; }
    
        public virtual tblUIModule tblUIModule { get; set; }
        public virtual ICollection<tblAction> tblActions { get; set; }
    }
}
