//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.Security.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUIModule
    {
        public tblUIModule()
        {
            this.tblBrokerModuleMappings = new HashSet<tblBrokerModuleMapping>();
            this.tblControllers = new HashSet<tblController>();
            this.tblActions = new HashSet<tblAction>();
            this.tblBrokerInformations = new HashSet<tblBrokerInformation>();
        }
    
        public decimal id { get; set; }
        public string name { get; set; }
        public string id_name { get; set; }
        public Nullable<decimal> sort_id { get; set; }
    
        public virtual ICollection<tblBrokerModuleMapping> tblBrokerModuleMappings { get; set; }
        public virtual ICollection<tblController> tblControllers { get; set; }
        public virtual ICollection<tblAction> tblActions { get; set; }
        public virtual ICollection<tblBrokerInformation> tblBrokerInformations { get; set; }
    }
}
