//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.Security.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblView
    {
        public tblView()
        {
            this.tblBrokerUserModules = new HashSet<tblBrokerUserModule>();
        }
    
        public decimal view_id { get; set; }
        public decimal module_id { get; set; }
        public string view_name { get; set; }
        public string router_name { get; set; }
        public string action_name { get; set; }
        public string area_name { get; set; }
    
        public virtual ICollection<tblBrokerUserModule> tblBrokerUserModules { get; set; }
    }
}
