//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Process.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProcessEntities : DbContext
    {
        public ProcessEntities()
            : base("name=ProcessEntities")
        {
            this.Database.CommandTimeout = this.Database.Connection.ConnectionTimeout;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimDate> DimDates { get; set; }
        public virtual DbSet<tblDayProcess> tblDayProcesses { get; set; }
    
        public virtual int psp_day_end(Nullable<decimal> process_dt, string end_by, Nullable<decimal> membership_id)
        {
            var process_dtParameter = process_dt.HasValue ?
                new ObjectParameter("process_dt", process_dt) :
                new ObjectParameter("process_dt", typeof(decimal));
    
            var end_byParameter = end_by != null ?
                new ObjectParameter("end_by", end_by) :
                new ObjectParameter("end_by", typeof(string));
    
            var membership_idParameter = membership_id.HasValue ?
                new ObjectParameter("membership_id", membership_id) :
                new ObjectParameter("membership_id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("psp_day_end", process_dtParameter, end_byParameter, membership_idParameter);
        }
    
        public virtual int psp_db_backup(string name, string path)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var pathParameter = path != null ?
                new ObjectParameter("path", path) :
                new ObjectParameter("path", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("psp_db_backup", nameParameter, pathParameter);
        }
    }
}
