//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InvestorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountClosing
    {
        public string client_id { get; set; }
        public decimal closing_date { get; set; }
        public string reason { get; set; }
        public decimal ledger_balance { get; set; }
        public decimal available_balance { get; set; }
        public decimal share_cost_value { get; set; }
        public decimal share_market_value { get; set; }
        public int active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual tblInvestor tblInvestor { get; set; }
    }
}
