//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InvestorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBankBranch
    {
        public tblBankBranch()
        {
            this.tblInvestors = new HashSet<tblInvestor>();
        }
    
        public decimal id { get; set; }
        public string branch_name { get; set; }
        public string routing_no { get; set; }
        public decimal bank_id { get; set; }
        public string address { get; set; }
        public string contact_person { get; set; }
        public string contact_number { get; set; }
        public string email_address { get; set; }
        public int active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
        public Nullable<decimal> district_id { get; set; }
    
        public virtual tblBank tblBank { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue { get; set; }
    }
}
