//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InvestorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvestorFinancialLedger
    {
        public decimal id { get; set; }
        public string client_id { get; set; }
        public string refference_no { get; set; }
        public decimal transaction_type_id { get; set; }
        public string narration { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> comm_amount { get; set; }
        public decimal debit { get; set; }
        public decimal credit { get; set; }
        public decimal transaction_date { get; set; }
        public int active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue { get; set; }
        public virtual tblInvestor tblInvestor { get; set; }
    }
}
