//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InvestorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvestorShareLedger
    {
        public decimal id { get; set; }
        public string client_id { get; set; }
        public decimal instrument_id { get; set; }
        public decimal transaction_date { get; set; }
        public decimal opening_qty { get; set; }
        public decimal opening_rate { get; set; }
        public decimal opening_cost { get; set; }
        public decimal received_qty { get; set; }
        public decimal received_rate { get; set; }
        public decimal received_cost { get; set; }
        public decimal delivery_qty { get; set; }
        public decimal delivery_rate { get; set; }
        public decimal delivery_cost { get; set; }
        public decimal sale_qty { get; set; }
        public decimal sale_value { get; set; }
        public decimal sale_commission { get; set; }
        public decimal sale_rate { get; set; }
        public decimal sale_amount { get; set; }
        public decimal sale_cost_rate { get; set; }
        public decimal sale_cost { get; set; }
        public decimal gain_loss { get; set; }
        public decimal remaining_qty { get; set; }
        public decimal remaining_rate { get; set; }
        public decimal remaining_cost { get; set; }
        public decimal buy_qty { get; set; }
        public decimal buy_cost { get; set; }
        public decimal buy_commission { get; set; }
        public decimal buy_rate { get; set; }
        public decimal buy_amount { get; set; }
        public decimal closing_qty { get; set; }
        public decimal closing_rate { get; set; }
        public decimal closing_cost { get; set; }
        public int active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual tblInvestor tblInvestor { get; set; }
    }
}
