//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InvestorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIntroducer
    {
        public tblIntroducer()
        {
            this.tblInvestors = new HashSet<tblInvestor>();
        }
    
        public decimal id { get; set; }
        public string ref_code { get; set; }
        public string introducer_name { get; set; }
        public decimal introducer_type_id { get; set; }
        public Nullable<decimal> occupation_id { get; set; }
        public string contact_no { get; set; }
        public string national_id { get; set; }
        public string tin { get; set; }
        public string remarks { get; set; }
        public decimal commission_percentage { get; set; }
        public decimal valid_from { get; set; }
        public decimal valid_to { get; set; }
        public int active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue1 { get; set; }
        public virtual tblIntroducer tblIntroducer1 { get; set; }
        public virtual tblIntroducer tblIntroducer2 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors { get; set; }
    }
}
