//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InvestorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNominee
    {
        public int id { get; set; }
        public string client_id { get; set; }
        public string nominee_name { get; set; }
        public string father_name { get; set; }
        public string mother_name { get; set; }
        public Nullable<decimal> birth_date { get; set; }
        public Nullable<decimal> open_date { get; set; }
        public Nullable<decimal> gender_id { get; set; }
        public Nullable<decimal> relation_id { get; set; }
        public string gurdian_name { get; set; }
        public string mailing_address { get; set; }
        public string permanent_address { get; set; }
        public string phone_no { get; set; }
        public string mobile_no { get; set; }
        public string email_address { get; set; }
        public Nullable<decimal> equity_percentage { get; set; }
        public byte[] photo { get; set; }
        public byte[] signature { get; set; }
        public int active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue1 { get; set; }
        public virtual tblInvestor tblInvestor { get; set; }
    }
}
