//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InvestorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOmnibu
    {
        public tblOmnibu()
        {
            this.tblInvestors = new HashSet<tblInvestor>();
        }
    
        public string omnibus_id { get; set; }
        public string name { get; set; }
        public string short_name { get; set; }
        public string contact_person { get; set; }
        public string contact_no { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public decimal active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
    
        public virtual tblConstantObjectValue tblConstantObjectValue { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors { get; set; }
    }
}
