//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InvestorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTrader
    {
        public tblTrader()
        {
            this.tblInvestors = new HashSet<tblInvestor>();
        }
    
        public decimal id { get; set; }
        public string trader_code { get; set; }
        public decimal employee_id { get; set; }
        public string ar_no { get; set; }
        public string trade_work_station { get; set; }
        public Nullable<decimal> license_renew_dt { get; set; }
        public int active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
        public decimal branch_id { get; set; }
        public Nullable<bool> Is_Default { get; set; }
        public string investor_range { get; set; }
    
        public virtual ICollection<tblInvestor> tblInvestors { get; set; }
        public virtual DimDate DimDate { get; set; }
    }
}
