//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InvestorManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_all_investors_charges
    {
        public string client_id { get; set; }
        public decimal global_charge_id { get; set; }
        public decimal charge_amount { get; set; }
        public decimal is_percentage { get; set; }
        public decimal minimum_charge { get; set; }
    }
}
