//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.AccountingManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConstantObjectValue
    {
        public tblConstantObjectValue()
        {
            this.tblBankBranches = new HashSet<tblBankBranch>();
        }
    
        public decimal object_value_id { get; set; }
        public string display_value { get; set; }
        public decimal object_id { get; set; }
        public string remarks { get; set; }
        public Nullable<short> sorting_order { get; set; }
        public Nullable<decimal> is_default { get; set; }
    
        public virtual ICollection<tblBankBranch> tblBankBranches { get; set; }
        public virtual tblConstantObject tblConstantObject { get; set; }
    }
}
