//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Service.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ServiceEntities : DbContext
    {
        public ServiceEntities()
            : base("name=ServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimDate> DimDates { get; set; }
        public virtual DbSet<tblInstrument> tblInstruments { get; set; }
        public virtual DbSet<tblInvestor> tblInvestors { get; set; }
        public virtual DbSet<tblPlaceOrder> tblPlaceOrders { get; set; }
    
        public virtual ObjectResult<ssp_pending_order_by_user_id_Result> ssp_pending_order_by_user_id(string user_id, Nullable<decimal> membership_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var membership_idParameter = membership_id.HasValue ?
                new ObjectParameter("membership_id", membership_id) :
                new ObjectParameter("membership_id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ssp_pending_order_by_user_id_Result>("ssp_pending_order_by_user_id", user_idParameter, membership_idParameter);
        }
    
        public virtual int rsp_client_portfolio_statement_as_on(Nullable<decimal> mEMBERSHIP_ID, string user_id, string cLIENT_ID, Nullable<System.DateTime> rEPORT_DATE)
        {
            var mEMBERSHIP_IDParameter = mEMBERSHIP_ID.HasValue ?
                new ObjectParameter("MEMBERSHIP_ID", mEMBERSHIP_ID) :
                new ObjectParameter("MEMBERSHIP_ID", typeof(decimal));
    
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var cLIENT_IDParameter = cLIENT_ID != null ?
                new ObjectParameter("CLIENT_ID", cLIENT_ID) :
                new ObjectParameter("CLIENT_ID", typeof(string));
    
            var rEPORT_DATEParameter = rEPORT_DATE.HasValue ?
                new ObjectParameter("REPORT_DATE", rEPORT_DATE) :
                new ObjectParameter("REPORT_DATE", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("rsp_client_portfolio_statement_as_on", mEMBERSHIP_IDParameter, user_idParameter, cLIENT_IDParameter, rEPORT_DATEParameter);
        }
    
        public virtual ObjectResult<ssp_placed_order_by_user_id_Result> ssp_placed_order_by_user_id(string user_id, Nullable<decimal> membership_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var membership_idParameter = membership_id.HasValue ?
                new ObjectParameter("membership_id", membership_id) :
                new ObjectParameter("membership_id", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ssp_placed_order_by_user_id_Result>("ssp_placed_order_by_user_id", user_idParameter, membership_idParameter);
        }
    }
}
