//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlaceOrder
    {
        public decimal id { get; set; }
        public string client_id { get; set; }
        public decimal instrument_id { get; set; }
        public string order_type { get; set; }
        public decimal quantity { get; set; }
        public decimal market_price { get; set; }
        public Nullable<decimal> negotiable { get; set; }
        public decimal order_date { get; set; }
        public string approve_by { get; set; }
        public Nullable<decimal> approve_date { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
        public string cancel_by { get; set; }
        public Nullable<decimal> cancel_date { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual tblInstrument tblInstrument { get; set; }
        public virtual tblInvestor tblInvestor { get; set; }
    }
}
