//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.CDBL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCdblIpo
    {
        public decimal ipo_id { get; set; }
        public string isin { get; set; }
        public string company_name { get; set; }
        public decimal trans_date { get; set; }
        public string bo_code { get; set; }
        public string bo_name { get; set; }
        public decimal qty { get; set; }
        public decimal lock_qty { get; set; }
        public decimal transaction_date { get; set; }
        public Nullable<int> active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
        public Nullable<decimal> unloak_date { get; set; }
        public Nullable<decimal> sold_qty { get; set; }
    }
}
