//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Transaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimDate
    {
        public DimDate()
        {
            this.tblBrokerBranches = new HashSet<tblBrokerBranch>();
            this.tblGlobalCharges = new HashSet<tblGlobalCharge>();
            this.tblFundWithdrawalRequests = new HashSet<tblFundWithdrawalRequest>();
            this.tblFundWithdrawalRequests1 = new HashSet<tblFundWithdrawalRequest>();
            this.tblFundWithdrawalRequests2 = new HashSet<tblFundWithdrawalRequest>();
            this.tblFundWithdrawalRequests3 = new HashSet<tblFundWithdrawalRequest>();
            this.tblInvestorFundBalances = new HashSet<tblInvestorFundBalance>();
            this.tblForceChargeApplies = new HashSet<tblForceChargeApply>();
            this.tblForceChargeApplies1 = new HashSet<tblForceChargeApply>();
            this.tblForceChargeApplies2 = new HashSet<tblForceChargeApply>();
            this.tblFundReceives = new HashSet<tblFundReceive>();
            this.tblFundReceives1 = new HashSet<tblFundReceive>();
            this.tblFundReceives2 = new HashSet<tblFundReceive>();
            this.tblFundReceives3 = new HashSet<tblFundReceive>();
            this.tblFundReceives4 = new HashSet<tblFundReceive>();
            this.tblFundReceives5 = new HashSet<tblFundReceive>();
            this.tblFundReceives6 = new HashSet<tblFundReceive>();
            this.tblInvestors = new HashSet<tblInvestor>();
            this.tblFundWithdraws = new HashSet<tblFundWithdraw>();
            this.tblFundWithdraws1 = new HashSet<tblFundWithdraw>();
            this.tblFundWithdraws2 = new HashSet<tblFundWithdraw>();
            this.tblFundWithdraws3 = new HashSet<tblFundWithdraw>();
            this.tblFundTransfers = new HashSet<tblFundTransfer>();
            this.tblFundTransfers1 = new HashSet<tblFundTransfer>();
            this.tblFundTransfers2 = new HashSet<tblFundTransfer>();
        }
    
        public decimal DateKey { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FullDateUK { get; set; }
        public string FullDateUSA { get; set; }
        public string DayOfMonth { get; set; }
        public string DaySuffix { get; set; }
        public string DayName { get; set; }
        public string DayOfWeekUSA { get; set; }
        public string DayOfWeekUK { get; set; }
        public string DayOfWeekInMonth { get; set; }
        public string DayOfWeekInYear { get; set; }
        public string DayOfQuarter { get; set; }
        public string DayOfYear { get; set; }
        public string WeekOfMonth { get; set; }
        public string WeekOfQuarter { get; set; }
        public string WeekOfYear { get; set; }
        public string Month { get; set; }
        public string MonthName { get; set; }
        public string MonthOfQuarter { get; set; }
        public string Quarter { get; set; }
        public string QuarterName { get; set; }
        public string Year { get; set; }
        public string YearName { get; set; }
        public string MonthYear { get; set; }
        public string MMYYYY { get; set; }
        public Nullable<System.DateTime> FirstDayOfMonth { get; set; }
        public Nullable<System.DateTime> LastDayOfMonth { get; set; }
        public Nullable<System.DateTime> FirstDayOfQuarter { get; set; }
        public Nullable<System.DateTime> LastDayOfQuarter { get; set; }
        public Nullable<System.DateTime> FirstDayOfYear { get; set; }
        public Nullable<System.DateTime> LastDayOfYear { get; set; }
        public Nullable<bool> IsHolidayUSA { get; set; }
        public Nullable<bool> IsWeekday { get; set; }
        public string HolidayUSA { get; set; }
        public Nullable<bool> IsHolidayUK { get; set; }
        public string HolidayUK { get; set; }
        public Nullable<bool> IsHoliday { get; set; }
        public string Holiday { get; set; }
        public string FiscalDayOfYear { get; set; }
        public string FiscalWeekOfYear { get; set; }
        public string FiscalMonth { get; set; }
        public string FiscalQuarter { get; set; }
        public string FiscalQuarterName { get; set; }
        public string FiscalYear { get; set; }
        public string FiscalYearName { get; set; }
        public string FiscalMonthYear { get; set; }
        public string FiscalMMYYYY { get; set; }
        public Nullable<System.DateTime> FiscalFirstDayOfMonth { get; set; }
        public Nullable<System.DateTime> FiscalLastDayOfMonth { get; set; }
        public Nullable<System.DateTime> FiscalFirstDayOfQuarter { get; set; }
        public Nullable<System.DateTime> FiscalLastDayOfQuarter { get; set; }
        public Nullable<System.DateTime> FiscalFirstDayOfYear { get; set; }
        public Nullable<System.DateTime> FiscalLastDayOfYear { get; set; }
        public string FullDateCDBL { get; set; }
    
        public virtual ICollection<tblBrokerBranch> tblBrokerBranches { get; set; }
        public virtual ICollection<tblGlobalCharge> tblGlobalCharges { get; set; }
        public virtual ICollection<tblFundWithdrawalRequest> tblFundWithdrawalRequests { get; set; }
        public virtual ICollection<tblFundWithdrawalRequest> tblFundWithdrawalRequests1 { get; set; }
        public virtual ICollection<tblFundWithdrawalRequest> tblFundWithdrawalRequests2 { get; set; }
        public virtual ICollection<tblFundWithdrawalRequest> tblFundWithdrawalRequests3 { get; set; }
        public virtual ICollection<tblInvestorFundBalance> tblInvestorFundBalances { get; set; }
        public virtual ICollection<tblForceChargeApply> tblForceChargeApplies { get; set; }
        public virtual ICollection<tblForceChargeApply> tblForceChargeApplies1 { get; set; }
        public virtual ICollection<tblForceChargeApply> tblForceChargeApplies2 { get; set; }
        public virtual ICollection<tblFundReceive> tblFundReceives { get; set; }
        public virtual ICollection<tblFundReceive> tblFundReceives1 { get; set; }
        public virtual ICollection<tblFundReceive> tblFundReceives2 { get; set; }
        public virtual ICollection<tblFundReceive> tblFundReceives3 { get; set; }
        public virtual ICollection<tblFundReceive> tblFundReceives4 { get; set; }
        public virtual ICollection<tblFundReceive> tblFundReceives5 { get; set; }
        public virtual ICollection<tblFundReceive> tblFundReceives6 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors { get; set; }
        public virtual ICollection<tblFundWithdraw> tblFundWithdraws { get; set; }
        public virtual ICollection<tblFundWithdraw> tblFundWithdraws1 { get; set; }
        public virtual ICollection<tblFundWithdraw> tblFundWithdraws2 { get; set; }
        public virtual ICollection<tblFundWithdraw> tblFundWithdraws3 { get; set; }
        public virtual ICollection<tblFundTransfer> tblFundTransfers { get; set; }
        public virtual ICollection<tblFundTransfer> tblFundTransfers1 { get; set; }
        public virtual ICollection<tblFundTransfer> tblFundTransfers2 { get; set; }
    }
}
