//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Transaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConstantObjectValue
    {
        public tblConstantObjectValue()
        {
            this.tblGlobalCharges = new HashSet<tblGlobalCharge>();
            this.tblFundWithdrawalRequests = new HashSet<tblFundWithdrawalRequest>();
            this.tblJoinHolders = new HashSet<tblJoinHolder>();
            this.tblJoinHolders1 = new HashSet<tblJoinHolder>();
            this.tblInvestorFundBalances = new HashSet<tblInvestorFundBalance>();
            this.tblForceChargeApplies = new HashSet<tblForceChargeApply>();
            this.tblFundReceives = new HashSet<tblFundReceive>();
            this.tblInvestors = new HashSet<tblInvestor>();
            this.tblInvestors1 = new HashSet<tblInvestor>();
            this.tblInvestors2 = new HashSet<tblInvestor>();
            this.tblInvestors3 = new HashSet<tblInvestor>();
            this.tblInvestors4 = new HashSet<tblInvestor>();
            this.tblInvestors5 = new HashSet<tblInvestor>();
            this.tblInvestors6 = new HashSet<tblInvestor>();
            this.tblInvestors7 = new HashSet<tblInvestor>();
            this.tblFundWithdraws = new HashSet<tblFundWithdraw>();
        }
    
        public decimal object_value_id { get; set; }
        public string display_value { get; set; }
        public decimal object_id { get; set; }
        public string remarks { get; set; }
        public Nullable<short> sorting_order { get; set; }
        public Nullable<decimal> is_default { get; set; }
    
        public virtual ICollection<tblGlobalCharge> tblGlobalCharges { get; set; }
        public virtual tblConstantObject tblConstantObject { get; set; }
        public virtual ICollection<tblFundWithdrawalRequest> tblFundWithdrawalRequests { get; set; }
        public virtual ICollection<tblJoinHolder> tblJoinHolders { get; set; }
        public virtual ICollection<tblJoinHolder> tblJoinHolders1 { get; set; }
        public virtual ICollection<tblInvestorFundBalance> tblInvestorFundBalances { get; set; }
        public virtual ICollection<tblForceChargeApply> tblForceChargeApplies { get; set; }
        public virtual ICollection<tblFundReceive> tblFundReceives { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors1 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors2 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors3 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors4 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors5 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors6 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors7 { get; set; }
        public virtual ICollection<tblFundWithdraw> tblFundWithdraws { get; set; }
    }
}
