//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Transaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFundTransfer
    {
        public decimal id { get; set; }
        public string transferor_id { get; set; }
        public decimal transferor_balance { get; set; }
        public string tranferee_id { get; set; }
        public decimal transferee_balance { get; set; }
        public decimal transfer_date { get; set; }
        public Nullable<decimal> value_date { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> charge_amount { get; set; }
        public string remarks { get; set; }
        public string approve_by { get; set; }
        public int active_status_id { get; set; }
        public Nullable<decimal> approve_date { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual DimDate DimDate2 { get; set; }
        public virtual tblInvestor tblInvestor { get; set; }
        public virtual tblInvestor tblInvestor1 { get; set; }
    }
}
