//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Transaction.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGlobalCharge
    {
        public tblGlobalCharge()
        {
            this.tblForceChargeApplies = new HashSet<tblForceChargeApply>();
        }
    
        public decimal id { get; set; }
        public string short_code { get; set; }
        public string name { get; set; }
        public decimal charge_amount { get; set; }
        public decimal minimum_charge { get; set; }
        public decimal is_percentage { get; set; }
        public decimal charge_type_id { get; set; }
        public decimal effective_date { get; set; }
        public decimal is_slab { get; set; }
        public string income_account_no { get; set; }
        public string payable_account_no { get; set; }
        public Nullable<decimal> payable_amount { get; set; }
        public Nullable<decimal> is_payable_percentage { get; set; }
        public int active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
    
        public virtual DimDate DimDate { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue { get; set; }
        public virtual ICollection<tblForceChargeApply> tblForceChargeApplies { get; set; }
    }
}
