//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Trade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFTOmnibusImportLog
    {
        public decimal log_id { get; set; }
        public string file_type { get; set; }
        public string file_name { get; set; }
        public decimal import_dt { get; set; }
        public decimal version_no { get; set; }
        public string success { get; set; }
        public string wrong { get; set; }
        public Nullable<decimal> export_st { get; set; }
        public Nullable<decimal> export_log_id { get; set; }
        public Nullable<decimal> membership_id { get; set; }
        public string omnibus_master_id { get; set; }
    
        public virtual DimDate DimDate { get; set; }
    }
}
