//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Trade.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNonTradingDetail
    {
        public decimal Id { get; set; }
        public decimal non_trading_date { get; set; }
        public int master_id { get; set; }
    
        public virtual DimDate DimDate { get; set; }
    }
}
