//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Configuration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accMapping
    {
        public decimal id { get; set; }
        public string gl_name { get; set; }
        public Nullable<long> ledger_head_id { get; set; }
    }
}
