//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Configuration.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ConfigurationConnection : DbContext
    {
        public ConfigurationConnection()
            : base("name=ConfigurationConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimDate> DimDates { get; set; }
        public virtual DbSet<tblBank> tblBanks { get; set; }
        public virtual DbSet<tblConstantObject> tblConstantObjects { get; set; }
        public virtual DbSet<tblConstantObjectValue> tblConstantObjectValues { get; set; }
        public virtual DbSet<tblBrokerBranch> tblBrokerBranches { get; set; }
        public virtual DbSet<tblDailyWorkList> tblDailyWorkLists { get; set; }
        public virtual DbSet<accMapping> accMappings { get; set; }
    
        [DbFunction("ConfigurationConnection", "tfun_get_ledger_head")]
        public virtual IQueryable<tfun_get_ledger_head_Result> tfun_get_ledger_head()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<tfun_get_ledger_head_Result>("[ConfigurationConnection].[tfun_get_ledger_head]()");
        }
    }
}
