//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Configuration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDailyWorkList
    {
        public decimal id { get; set; }
        public string work_name { get; set; }
        public decimal sort_order { get; set; }
        public decimal membership_id { get; set; }
        public decimal is_done { get; set; }
    }
}
