//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Charge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBrokerBranch
    {
        public tblBrokerBranch()
        {
            this.tblBranchCharges = new HashSet<tblBranchCharge>();
            this.tblBranchAccountTypeSettings = new HashSet<tblBranchAccountTypeSetting>();
        }
    
        public decimal id { get; set; }
        public string name { get; set; }
        public string ipo_branch_code { get; set; }
        public string address { get; set; }
        public string contact_person { get; set; }
        public string contact_no { get; set; }
        public string email { get; set; }
        public decimal registration_dt { get; set; }
        public int active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
    
        public virtual ICollection<tblBranchCharge> tblBranchCharges { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual ICollection<tblBranchAccountTypeSetting> tblBranchAccountTypeSettings { get; set; }
    }
}
