//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Charge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConstantObjectValue
    {
        public tblConstantObjectValue()
        {
            this.tblGlobalCharges = new HashSet<tblGlobalCharge>();
            this.tblSubAccountCharges = new HashSet<tblSubAccountCharge>();
            this.tblExchangeCharges = new HashSet<tblExchangeCharge>();
            this.tblBranchAccountTypeSettings = new HashSet<tblBranchAccountTypeSetting>();
            this.tblBranchAccountTypeSettings1 = new HashSet<tblBranchAccountTypeSetting>();
            this.tblBranchAccountTypeSettings2 = new HashSet<tblBranchAccountTypeSetting>();
            this.tblBranchAccountTypeSettings3 = new HashSet<tblBranchAccountTypeSetting>();
            this.tblBranchAccountTypeSettings4 = new HashSet<tblBranchAccountTypeSetting>();
            this.tblGlobalAccountTypeSettings = new HashSet<tblGlobalAccountTypeSetting>();
            this.tblGlobalAccountTypeSettings1 = new HashSet<tblGlobalAccountTypeSetting>();
            this.tblGlobalAccountTypeSettings2 = new HashSet<tblGlobalAccountTypeSetting>();
            this.tblGlobalAccountTypeSettings3 = new HashSet<tblGlobalAccountTypeSetting>();
            this.tblInvestorAccountTypeSettings = new HashSet<tblInvestorAccountTypeSetting>();
            this.tblInvestorAccountTypeSettings1 = new HashSet<tblInvestorAccountTypeSetting>();
            this.tblInvestorAccountTypeSettings2 = new HashSet<tblInvestorAccountTypeSetting>();
            this.tblInvestorAccountTypeSettings3 = new HashSet<tblInvestorAccountTypeSetting>();
            this.tblInvestorAccountTypeSettings4 = new HashSet<tblInvestorAccountTypeSetting>();
            this.tblSubAccountAccountTypeSettings = new HashSet<tblSubAccountAccountTypeSetting>();
            this.tblSubAccountAccountTypeSettings1 = new HashSet<tblSubAccountAccountTypeSetting>();
            this.tblSubAccountAccountTypeSettings2 = new HashSet<tblSubAccountAccountTypeSetting>();
            this.tblSubAccountAccountTypeSettings3 = new HashSet<tblSubAccountAccountTypeSetting>();
            this.tblSubAccountAccountTypeSettings4 = new HashSet<tblSubAccountAccountTypeSetting>();
            this.tblSubAccountAccountTypeSettings5 = new HashSet<tblSubAccountAccountTypeSetting>();
        }
    
        public decimal object_value_id { get; set; }
        public string display_value { get; set; }
        public decimal object_id { get; set; }
        public string remarks { get; set; }
        public Nullable<short> sorting_order { get; set; }
        public Nullable<decimal> is_default { get; set; }
    
        public virtual ICollection<tblGlobalCharge> tblGlobalCharges { get; set; }
        public virtual ICollection<tblSubAccountCharge> tblSubAccountCharges { get; set; }
        public virtual tblConstantObject tblConstantObject { get; set; }
        public virtual ICollection<tblExchangeCharge> tblExchangeCharges { get; set; }
        public virtual ICollection<tblBranchAccountTypeSetting> tblBranchAccountTypeSettings { get; set; }
        public virtual ICollection<tblBranchAccountTypeSetting> tblBranchAccountTypeSettings1 { get; set; }
        public virtual ICollection<tblBranchAccountTypeSetting> tblBranchAccountTypeSettings2 { get; set; }
        public virtual ICollection<tblBranchAccountTypeSetting> tblBranchAccountTypeSettings3 { get; set; }
        public virtual ICollection<tblBranchAccountTypeSetting> tblBranchAccountTypeSettings4 { get; set; }
        public virtual ICollection<tblGlobalAccountTypeSetting> tblGlobalAccountTypeSettings { get; set; }
        public virtual ICollection<tblGlobalAccountTypeSetting> tblGlobalAccountTypeSettings1 { get; set; }
        public virtual ICollection<tblGlobalAccountTypeSetting> tblGlobalAccountTypeSettings2 { get; set; }
        public virtual ICollection<tblGlobalAccountTypeSetting> tblGlobalAccountTypeSettings3 { get; set; }
        public virtual tblGlobalAccountTypeSetting tblGlobalAccountTypeSetting { get; set; }
        public virtual ICollection<tblInvestorAccountTypeSetting> tblInvestorAccountTypeSettings { get; set; }
        public virtual ICollection<tblInvestorAccountTypeSetting> tblInvestorAccountTypeSettings1 { get; set; }
        public virtual ICollection<tblInvestorAccountTypeSetting> tblInvestorAccountTypeSettings2 { get; set; }
        public virtual ICollection<tblInvestorAccountTypeSetting> tblInvestorAccountTypeSettings3 { get; set; }
        public virtual ICollection<tblInvestorAccountTypeSetting> tblInvestorAccountTypeSettings4 { get; set; }
        public virtual ICollection<tblSubAccountAccountTypeSetting> tblSubAccountAccountTypeSettings { get; set; }
        public virtual ICollection<tblSubAccountAccountTypeSetting> tblSubAccountAccountTypeSettings1 { get; set; }
        public virtual ICollection<tblSubAccountAccountTypeSetting> tblSubAccountAccountTypeSettings2 { get; set; }
        public virtual ICollection<tblSubAccountAccountTypeSetting> tblSubAccountAccountTypeSettings3 { get; set; }
        public virtual ICollection<tblSubAccountAccountTypeSetting> tblSubAccountAccountTypeSettings4 { get; set; }
        public virtual ICollection<tblSubAccountAccountTypeSetting> tblSubAccountAccountTypeSettings5 { get; set; }
    }
}
