//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.Charge.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvestorChargeSlab
    {
        public decimal id { get; set; }
        public decimal investor_charge_id { get; set; }
        public decimal amount_from { get; set; }
        public decimal amount_to { get; set; }
        public decimal charge_amount { get; set; }
        public decimal is_percentage { get; set; }
    
        public virtual tblInvestorCharge tblInvestorCharge { get; set; }
    }
}
