//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InstrumentManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InstrumentManagementConnection : DbContext
    {
        public InstrumentManagementConnection()
            : base("name=InstrumentManagementConnection")
        {
            this.Database.CommandTimeout = this.Database.Connection.ConnectionTimeout;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimDate> DimDates { get; set; }
        public virtual DbSet<tblConstantObject> tblConstantObjects { get; set; }
        public virtual DbSet<tblConstantObjectValue> tblConstantObjectValues { get; set; }
        public virtual DbSet<tblInstrument> tblInstruments { get; set; }
        public virtual DbSet<tblInstrumentFundamentalInfo> tblInstrumentFundamentalInfoes { get; set; }
        public virtual DbSet<tblInstrumentMarginabilityHistory> tblInstrumentMarginabilityHistories { get; set; }
        public virtual DbSet<tblInstrumentManualInOut> tblInstrumentManualInOuts { get; set; }
        public virtual DbSet<vw_InvestorShareBalance> vw_InvestorShareBalance { get; set; }
        public virtual DbSet<vw_all_investors_account_type_setting> vw_all_investors_account_type_setting { get; set; }
    
        public virtual int psp_investor_share_transaction(string id, Nullable<decimal> sHARE_LEDGER_TYPE_ID, Nullable<decimal> membership_id, string changed_user_id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var sHARE_LEDGER_TYPE_IDParameter = sHARE_LEDGER_TYPE_ID.HasValue ?
                new ObjectParameter("SHARE_LEDGER_TYPE_ID", sHARE_LEDGER_TYPE_ID) :
                new ObjectParameter("SHARE_LEDGER_TYPE_ID", typeof(decimal));
    
            var membership_idParameter = membership_id.HasValue ?
                new ObjectParameter("membership_id", membership_id) :
                new ObjectParameter("membership_id", typeof(decimal));
    
            var changed_user_idParameter = changed_user_id != null ?
                new ObjectParameter("changed_user_id", changed_user_id) :
                new ObjectParameter("changed_user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("psp_investor_share_transaction", idParameter, sHARE_LEDGER_TYPE_IDParameter, membership_idParameter, changed_user_idParameter);
        }
    }
}
