//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InstrumentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConstantObjectValue
    {
        public tblConstantObjectValue()
        {
            this.tblInstruments = new HashSet<tblInstrument>();
            this.tblInstruments1 = new HashSet<tblInstrument>();
            this.tblInstruments2 = new HashSet<tblInstrument>();
            this.tblInstruments3 = new HashSet<tblInstrument>();
            this.tblInstrumentManualInOuts = new HashSet<tblInstrumentManualInOut>();
        }
    
        public decimal object_value_id { get; set; }
        public string display_value { get; set; }
        public decimal object_id { get; set; }
        public string remarks { get; set; }
        public Nullable<short> sorting_order { get; set; }
        public Nullable<decimal> is_default { get; set; }
    
        public virtual tblConstantObject tblConstantObject { get; set; }
        public virtual ICollection<tblInstrument> tblInstruments { get; set; }
        public virtual ICollection<tblInstrument> tblInstruments1 { get; set; }
        public virtual ICollection<tblInstrument> tblInstruments2 { get; set; }
        public virtual ICollection<tblInstrument> tblInstruments3 { get; set; }
        public virtual ICollection<tblInstrumentManualInOut> tblInstrumentManualInOuts { get; set; }
    }
}
