//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.InstrumentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstrument
    {
        public tblInstrument()
        {
            this.tblInstrumentFundamentalInfoes = new HashSet<tblInstrumentFundamentalInfo>();
            this.tblInstrumentMarginabilityHistories = new HashSet<tblInstrumentMarginabilityHistory>();
            this.tblInstrumentManualInOuts = new HashSet<tblInstrumentManualInOut>();
        }
    
        public decimal id { get; set; }
        public string isin { get; set; }
        public string security_code { get; set; }
        public string instrument_name { get; set; }
        public decimal sector_id { get; set; }
        public decimal instument_type_id { get; set; }
        public decimal depository_company_id { get; set; }
        public decimal face_value { get; set; }
        public Nullable<decimal> discount { get; set; }
        public Nullable<decimal> premium { get; set; }
        public decimal lot { get; set; }
        public decimal is_marginable { get; set; }
        public decimal group_id { get; set; }
        public Nullable<decimal> closed_price { get; set; }
        public decimal is_foreign { get; set; }
        public Nullable<decimal> authorized_capital { get; set; }
        public Nullable<decimal> paid_up_capital { get; set; }
        public Nullable<decimal> current_eps { get; set; }
        public Nullable<decimal> current_nav { get; set; }
        public Nullable<decimal> current_pe { get; set; }
        public int active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
        public Nullable<decimal> market_type_id { get; set; }
    
        public virtual tblConstantObjectValue tblConstantObjectValue { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue1 { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue2 { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue3 { get; set; }
        public virtual ICollection<tblInstrumentFundamentalInfo> tblInstrumentFundamentalInfoes { get; set; }
        public virtual ICollection<tblInstrumentMarginabilityHistory> tblInstrumentMarginabilityHistories { get; set; }
        public virtual ICollection<tblInstrumentManualInOut> tblInstrumentManualInOuts { get; set; }
    }
}
