//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.BrokerManagement.Models
{
    using System;
    
    public partial class ssp_get_investor_info_Result1
    {
        public string client_id { get; set; }
        public string bo_code { get; set; }
        public string first_holder_name { get; set; }
        public decimal trader_id { get; set; }
    }
}
