//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.BrokerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConstantObjectValue
    {
        public tblConstantObjectValue()
        {
            this.tblEmployees = new HashSet<tblEmployee>();
            this.tblEmployees1 = new HashSet<tblEmployee>();
            this.tblEmployees2 = new HashSet<tblEmployee>();
            this.tblInvestors = new HashSet<tblInvestor>();
            this.tblInvestors1 = new HashSet<tblInvestor>();
            this.tblInvestors2 = new HashSet<tblInvestor>();
            this.tblInvestors3 = new HashSet<tblInvestor>();
            this.tblInvestors4 = new HashSet<tblInvestor>();
            this.tblInvestors5 = new HashSet<tblInvestor>();
            this.tblInvestors6 = new HashSet<tblInvestor>();
            this.tblInvestors7 = new HashSet<tblInvestor>();
        }
    
        public decimal object_value_id { get; set; }
        public string display_value { get; set; }
        public decimal object_id { get; set; }
        public string remarks { get; set; }
        public Nullable<short> sorting_order { get; set; }
        public Nullable<decimal> is_default { get; set; }
    
        public virtual tblConstantObject tblConstantObject { get; set; }
        public virtual ICollection<tblEmployee> tblEmployees { get; set; }
        public virtual ICollection<tblEmployee> tblEmployees1 { get; set; }
        public virtual ICollection<tblEmployee> tblEmployees2 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors1 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors2 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors3 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors4 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors5 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors6 { get; set; }
        public virtual ICollection<tblInvestor> tblInvestors7 { get; set; }
    }
}
