//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escrow.BOAS.BrokerManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        public tblEmployee()
        {
            this.tblEmployeeUserMappings = new HashSet<tblEmployeeUserMapping>();
            this.tblTraders = new HashSet<tblTrader>();
        }
    
        public decimal id { get; set; }
        public string employee_code { get; set; }
        public string name { get; set; }
        public string father_name { get; set; }
        public string national_id { get; set; }
        public decimal branch_id { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string mailing_address { get; set; }
        public string permanent_address { get; set; }
        public string contact_no { get; set; }
        public string ref1_details { get; set; }
        public string ref2_details { get; set; }
        public decimal department_id { get; set; }
        public Nullable<decimal> joining_dt { get; set; }
        public Nullable<decimal> release_dt { get; set; }
        public decimal designation_id { get; set; }
        public decimal gender_id { get; set; }
        public string email_address { get; set; }
        public int active_status_id { get; set; }
        public decimal membership_id { get; set; }
        public string changed_user_id { get; set; }
        public System.DateTime changed_date { get; set; }
        public decimal is_dirty { get; set; }
        public string mother_name { get; set; }
        public byte[] photo { get; set; }
    
        public virtual tblConstantObjectValue tblConstantObjectValue { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue1 { get; set; }
        public virtual tblConstantObjectValue tblConstantObjectValue2 { get; set; }
        public virtual DimDate DimDate { get; set; }
        public virtual DimDate DimDate1 { get; set; }
        public virtual ICollection<tblEmployeeUserMapping> tblEmployeeUserMappings { get; set; }
        public virtual ICollection<tblTrader> tblTraders { get; set; }
        public virtual tblBrokerBranch tblBrokerBranch { get; set; }
    }
}
